### ISSUE TITLE
Multi-window support

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_port_pc_visual_studio#55]
Hi,

I wonder if it's possible to create 2 windows for 2 `lv_disp_t` instances with Visual Studio.

It would be very useful for a particular project where we have the normal UI in one window and we add some slider to simulate data changes in an other window.

**Comment by MouriNaruto** [comment]
Yes, it's possible to create 2 windows.

Kenji Mouri

**Comment by kisvegabor** [comment]
Great! Could you shown an example for that? Or shall we just call `lv_win32_init` again?

**Comment by MouriNaruto** [comment]
I will add the example for that as soon as possible. Please wait for a while. If it's OK, I will update the progress in this issue.

Kenji Mouri

**Comment by kisvegabor** [comment]
Thank you, Kenji!

**Comment by MouriNaruto** [comment]
The multi window support actually added in LVGL 9.x's Windows backend.

Kenji Mouri
