### ISSUE TITLE
Visual Studio Version

### ISSUE THREAD

**Issue by tbjr16** [lvgl/lv_port_pc_visual_studio#59]
In the readme it says to use Visual Studio 2019. When compiling it says it needs .Net 7 which is only available in 2022, by Microsoft's documentation. Either the readme or .net minimum version should be changed in case someone else new to LVGL follows the readme.

**Comment by MouriNaruto** [comment]
You don't need to care about these C# projects because they're maintainer-specific projects. (Help project maintainers to maintain the source code of this repository.)

Kenji Mouri

**Comment by MouriNaruto** [comment]
Close this issue due to no further replies.

Kenji Mouri
