### ISSUE TITLE
Render Issue

### ISSUE THREAD

**Issue by xland** [lvgl/lv_port_pc_visual_studio#60]
Windows 10 19044.2846

lv_port_pc_visual_studio main branch

![image](https://github.com/lvgl/lv_port_pc_visual_studio/assets/2980915/ad2e1447-f55e-4b2d-bcdd-e2505a2ff157)

In addition to this

When I drag the mouse to change the window size, it causes the application crash.

**Comment by MouriNaruto** [comment]
The backend in desktop application demo is deprecated in the future.

The new backend implementation in the simulator demo and it supports all features in desktop application demo.

If the new backend is finished, I will push them to the LVGL mainline.

Kenji Mouri

**Comment by MouriNaruto** [comment]
The new backend is merged in the LVGL mainline.

https://github.com/lvgl/lvgl/pull/5313

Kenji Mouri
