### ISSUE TITLE
when i update the lvgl to the newest version, many errors!!

### ISSUE THREAD

**Issue by xinsuinizhuan** [lvgl/lv_port_pc_visual_studio#65]
1、lv_indev_get_disp not define
error as:
win32drv.obj : error LNK2019: 无法解析的外部符号 lv_indev_get_disp，函数 lv_windows_get_indev_window_handle 中引用了该符号
2、not show ui, tips:
 _lv_display_refr_timer: No draw buffer lv_refr.c:350

**Comment by xinsuinizhuan** [comment]
new verison has no lv_indev_get_disp,but in win32drv.chas the function:
![图片](https://github.com/lvgl/lv_port_pc_visual_studio/assets/40679769/dbb25fd0-0010-4fd2-bac8-9a03b1cb84f7)

**Comment by MouriNaruto** [comment]
Because LVGL's new main branch changed some ABI. I need to follow. Please wait.

Kenji Mouri

**Comment by MouriNaruto** [comment]
https://github.com/lvgl/lvgl/commit/e10f573150a95822df6422541bcc9ea1238f098a#diff-35a05ebbf5595318ed115bcabc7f70e6ae0b4f1f3ace3629e154a7434fe680f1

It looks the yesterday's LVGL mainline changed a lot of API namings.

Kenji Mouri

**Comment by MouriNaruto** [comment]
https://github.com/lvgl/lv_port_pc_visual_studio/commit/aa94c0504b8e1a1836d424723c46044cba5f5ee6

It should be fixed after this commit.

Kenji Mouri

**Comment by xinsuinizhuan** [comment]
still error:
when i update the newest version, open the .sln，then errors:
c1 : fatal error C1083: coould not open: “E:\lvgl\git\lv_port_pc_visual_studio-master\LvglPlatform\lvgl\src\draw\renesas\dave2d\lv_draw_dave2d_uitls.c”: No such file or directory

**Comment by xinsuinizhuan** [comment]
still:
![图片](https://github.com/lvgl/lv_port_pc_visual_studio/assets/40679769/3f1066ec-f3d1-48c4-82e3-d08b0475a069)

**Comment by xinsuinizhuan** [comment]
still:
![图片](https://github.com/lvgl/lv_port_pc_visual_studio/assets/40679769/8bacfc44-929d-4537-a54a-0b47bc423fff)

**Comment by MouriNaruto** [comment]
I don't think you have updated the newest version of this repository.

Because this old issue I have fixed.

Kenji Mouri

**Comment by MouriNaruto** [comment]
![image](https://github.com/lvgl/lv_port_pc_visual_studio/assets/10867563/8f58721d-bd71-4546-a57b-0833c0cdada5)

With the GitHub search feature, you will know I fixed this issue.

Kenji Mouri

**Comment by MouriNaruto** [comment]
Close this issue due to no further replies.

Kenji Mouri
