### ISSUE TITLE
 lastest version, lv_demo_benchmark BREAK. VS2019

### ISSUE THREAD

**Issue by NewObject404** [lvgl/lv_port_pc_visual_studio#66]
![图片](https://github.com/lvgl/lv_port_pc_visual_studio/assets/75886646/334ee328-d3ec-46a6-be3f-22253b329418)
![图片](https://github.com/lvgl/lv_port_pc_visual_studio/assets/75886646/89cab0c2-d98c-4694-8ee6-52e68209e4d1)

**Comment by MouriNaruto** [comment]
It seems not be the latest version. Please sync repo again.

P.S. Title name has been changed after the Windows backend merged to the LVGL mainline.

Kenji Mouri

**Comment by NewObject404** [comment]
> It seems not be the latest version. Please sync repo again.
> 
> P.S. Title name has been changed after the Windows backend merged to the LVGL mainline.
> 
> Kenji Mouri

You are right! resync repo,test pass!
