### ISSUE TITLE
可以在windows应用中增加一个缩小到系统托盘的功能吗

### ISSUE THREAD

**Issue by jinsc123654** [lvgl/lv_port_pc_visual_studio#68]
我想使用lvgl做一个windows小工具，它需要在后台运行，但是lvgl缩小后是在下方导航栏
我需要把lvgl的应用收进系统托盘栏，请问我需要怎么去修改对应源码
类型下方的缩小进系统导航栏
![image](https://github.com/lvgl/lv_port_pc_visual_studio/assets/53360341/0521fa02-93f1-4bb2-bcc2-868c8312aeb2)

**Comment by kisvegabor** [comment]
Please write in English. Using a translator is fine too.

**Comment by jinsc123654** [comment]
Chinese translation:
I want to use lvgl to create a Windows mini tool that needs to run in the background, but when lvgl is scaled down, it will appear in the navigation bar below
I need to put the lvgl application into the system tray. May I know how to modify the corresponding source code
Zoom out to the system navigation bar below the type


I have already implemented this function myself, thank you
![image](https://github.com/lvgl/lv_port_pc_visual_studio/assets/53360341/a0edc0b5-1f10-42e4-83fd-33b273798a68)
