### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by xinsuinizhuan** [lvgl/lv_port_pc_visual_studio#69]
one:
the windows application,max frame, the meter pointer is offline:
![图片](https://github.com/lvgl/lv_port_pc_visual_studio/assets/40679769/6654da85-6c5c-418d-8601-34bbea088894)

two:
the newest lvgl code， lv_image_header_cache_drop function is missing

third:
when max frame, close the frame, break:
![图片](https://github.com/lvgl/lv_port_pc_visual_studio/assets/40679769/37221db8-bc37-41e7-a95d-456dc020aeb6)

**Comment by MouriNaruto** [comment]
For the meter pointer, you need to ask for the widget demo in LVGL for resolution change support.

For the crash issue, I will try to solve.

Kenji Mouri

**Comment by kisvegabor** [comment]
> For the meter pointer, you need to ask for the widget demo in LVGL for resolution change support.

Yeah, it's not fully responsive. :slightly_frowning_face:

**Comment by MouriNaruto** [comment]
Close this issue due to no further replies.

Kenji Mouri
