### ISSUE TITLE
Getting RLottie to work

### ISSUE THREAD

**Issue by tank104** [lvgl/lv_port_pc_visual_studio#73]
Has anyone been able to get rlottie to work?

I enabled LV_USE_RLOTTIE = 1

But get the error below.

That file is in https://github.com/Samsung/rlottie/tree/master/inc but not included in this, and I am unsure how I should best include it?

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C1083	Cannot open include file: 'rlottie_capi.h': No such file or directory	LvglWindowsStatic	C:\github\lv_port_pc_visual_studio\LvglPlatform\lvgl\src\libs\rlottie\lv_rlottie.c	12

**Comment by kisvegabor** [comment]
Hi,

If you are using LVGL v9 I suggest using the new [Lottie library](https://docs.lvgl.io/master/widgets/lottie.html). It works with ThorVG which is integrated into LVGL.

**Comment by tank104** [comment]
@kisvegabor thanks for this info - probably raises more questions than answers ;-)

Is there an example of this for the LV Port PC - I had a quick look and couldn't find anything.

**Comment by tank104** [comment]
Ignore that - have found the examples - I had an older version of lvgl which is why I couldn't see them.

Got it all working now thanks!

**Comment by kisvegabor** [comment]
Fantastic! :slightly_smiling_face:
