### ISSUE TITLE
I can't find LvglWindowsSimulator.sln file ...

### ISSUE THREAD

**Issue by AlbCod** [lvgl/lv_port_pc_visual_studio#75]
It's definitely due to my inexperience but I can't find the LvglWindowsSimulator.sln file to open in Visual Studio.

Step: How To Build & Run
"Open the LvglWindowsSimulator.sln solution file in Visual Studio."

Thanks for your help
Alberto

**Comment by MouriNaruto** [comment]
The solution file is renamed to LVGL.sln.

I will update the document.

Kenji Mouri

**Comment by AlbCod** [comment]
Ok thanks
